2021-04-04 12:04:36,571 INFO:         Microblog starting up [in /Users/inwaves/inwaves-repository/microblog/app/__init__.py:56]
2021-04-04 12:04:39,842 INFO:         Microblog starting up [in /Users/inwaves/inwaves-repository/microblog/app/__init__.py:56]
2021-04-04 12:04:44,207 INFO:         Microblog starting up [in /Users/inwaves/inwaves-repository/microblog/app/__init__.py:56]
2021-04-04 13:12:06,407 INFO:         Microblog starting up [in /Users/inwaves/inwaves-repository/microblog/app/__init__.py:56]
2021-04-04 13:12:29,292 INFO:         Microblog starting up [in /Users/inwaves/inwaves-repository/microblog/app/__init__.py:56]
2021-04-04 13:14:20,367 INFO:         Microblog starting up [in /Users/inwaves/inwaves-repository/microblog/app/__init__.py:56]
2021-04-04 13:18:46,967 INFO:         Microblog starting up [in /Users/inwaves/inwaves-repository/microblog/app/__init__.py:56]
2021-04-04 13:19:27,645 INFO:         Microblog starting up [in /Users/inwaves/inwaves-repository/microblog/app/__init__.py:56]
2021-04-04 13:19:59,874 INFO:         Microblog starting up [in /Users/inwaves/inwaves-repository/microblog/app/__init__.py:56]
2021-04-04 13:20:13,807 INFO:         Microblog starting up [in /Users/inwaves/inwaves-repository/microblog/app/__init__.py:56]
2021-04-04 13:20:22,258 INFO:         Microblog starting up [in /Users/inwaves/inwaves-repository/microblog/app/__init__.py:56]
2021-04-04 13:20:38,633 INFO:         Microblog starting up [in /Users/inwaves/inwaves-repository/microblog/app/__init__.py:56]
2021-04-04 14:36:16,815 INFO:         Microblog starting up [in /Users/inwaves/inwaves-repository/microblog/app/__init__.py:56]
2021-04-04 14:42:13,671 INFO:         Microblog starting up [in /Users/inwaves/inwaves-repository/microblog/app/__init__.py:56]
2021-04-04 14:42:21,847 INFO:         Microblog starting up [in /Users/inwaves/inwaves-repository/microblog/app/__init__.py:56]
2021-04-04 14:54:49,211 INFO:         Microblog starting up [in /Users/inwaves/inwaves-repository/microblog/app/__init__.py:56]
2021-04-04 14:54:55,633 INFO:         Microblog starting up [in /Users/inwaves/inwaves-repository/microblog/app/__init__.py:56]
2021-04-04 15:12:31,938 INFO:         Microblog starting up [in /Users/inwaves/inwaves-repository/microblog/app/__init__.py:56]
2021-04-04 15:12:34,865 INFO:         Microblog starting up [in /Users/inwaves/inwaves-repository/microblog/app/__init__.py:56]
2021-04-04 15:12:37,015 ERROR:         Exception on / [GET] [in /Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/inwaves/inwaves-repository/microblog/app/routes.py", line 33, in index
    return render_template("index.html", title="Home Page", form=form, todos=tasks)
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/inwaves/inwaves-repository/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/inwaves/inwaves-repository/microblog/app/templates/base.html", line 43, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/inwaves/inwaves-repository/microblog/app/templates/index.html", line 15, in block "content"
    {{ form.post(cols=32, rows=4) }} <br>
jinja2.exceptions.UndefinedError: 'app.forms.PostForm object' has no attribute 'post'
2021-04-04 15:13:07,332 INFO:         Microblog starting up [in /Users/inwaves/inwaves-repository/microblog/app/__init__.py:56]
2021-04-04 15:13:09,445 ERROR:         Exception on / [GET] [in /Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/inwaves/inwaves-repository/microblog/app/routes.py", line 33, in index
    return render_template("index.html", title="Home Page", form=form, todos=tasks)
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/inwaves/inwaves-repository/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/inwaves/inwaves-repository/microblog/app/templates/base.html", line 43, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/inwaves/inwaves-repository/microblog/app/templates/index.html", line 16, in block "content"
    {% for error in form.post.errors %}
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.PostForm object' has no attribute 'post'
2021-04-04 15:13:39,871 INFO:         Microblog starting up [in /Users/inwaves/inwaves-repository/microblog/app/__init__.py:56]
2021-04-04 15:14:57,323 INFO:         Microblog starting up [in /Users/inwaves/inwaves-repository/microblog/app/__init__.py:56]
