2021-04-10 15:21:51,047 ERROR: Unhandled exception [in ./app/jobs.py:52]
Traceback (most recent call last):
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/smtplib.py", line 856, in sendmail
    self.ehlo_or_helo_if_needed()
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/smtplib.py", line 604, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/smtplib.py", line 444, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/smtplib.py", line 371, in putcmd
    self.send(str)
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/smtplib.py", line 363, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./app/jobs.py", line 44, in export_tasks
    send_email("[Microtasks] Your tasks", sender=app.config["ADMINS"][0],
  File "./app/mail_framework.py", line 23, in send_email
    mail.send(msg)
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/smtplib.py", line 988, in quit
    res = self.docmd("quit")
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/smtplib.py", line 424, in docmd
    self.putcmd(cmd, args)
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/smtplib.py", line 371, in putcmd
    self.send(str)
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/smtplib.py", line 363, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
2021-04-10 15:25:03,282 INFO: Microblog startup [in /Users/inwaves/inwaves-repository/o.microtasks/app/__init__.py:92]
2021-04-10 15:25:08,471 INFO: Microblog startup [in ./app/__init__.py:92]
2021-04-10 15:27:18,820 INFO: Microblog startup [in /Users/inwaves/inwaves-repository/o.microtasks/app/__init__.py:92]
2021-04-10 15:27:24,930 INFO: Microblog startup [in /Users/inwaves/inwaves-repository/o.microtasks/app/__init__.py:92]
2021-04-10 15:27:28,907 INFO: Microblog startup [in /Users/inwaves/inwaves-repository/o.microtasks/app/__init__.py:92]
2021-04-10 15:27:30,711 INFO: Microblog startup [in /Users/inwaves/inwaves-repository/o.microtasks/app/__init__.py:92]
2021-04-10 15:27:38,505 INFO: Microblog startup [in ./app/__init__.py:92]
2021-04-10 18:25:55,601 INFO: Microblog startup [in /Users/inwaves/inwaves-repository/o.microtasks/app/__init__.py:92]
2021-04-10 18:26:07,260 INFO: Microblog startup [in /Users/inwaves/inwaves-repository/o.microtasks/app/__init__.py:92]
2021-04-10 18:28:18,518 INFO: Microblog startup [in ./app/__init__.py:92]
